// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Timer

#ifndef _TIMER_UI_H
#define _TIMER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_leftPanel;
extern lv_obj_t * ui_leftSegment;
extern lv_obj_t * ui_rightPanel;
extern lv_obj_t * ui_rightSegment;
extern lv_obj_t * ui_middleSpace;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_S52);
LV_FONT_DECLARE(ui_font_SS52);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
