// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftSeg = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_leftSeg, 51);
    lv_obj_set_height(ui_leftSeg, 53);
    lv_obj_set_x(ui_leftSeg, -28);
    lv_obj_set_y(ui_leftSeg, 0);
    lv_obj_set_align(ui_leftSeg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftSeg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftSeg, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_leftSeg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftSeg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftText = lv_label_create(ui_leftSeg);
    lv_obj_set_width(ui_leftText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leftText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_leftText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_leftText, "10");
    lv_obj_set_style_text_color(ui_leftText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_leftText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_leftText, &ui_font_SS48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightSeg = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_rightSeg, 51);
    lv_obj_set_height(ui_rightSeg, 53);
    lv_obj_set_x(ui_rightSeg, 28);
    lv_obj_set_y(ui_rightSeg, 0);
    lv_obj_set_align(ui_rightSeg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightSeg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightSeg, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rightSeg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rightSeg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rightSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightText = lv_label_create(ui_rightSeg);
    lv_obj_set_width(ui_rightText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rightText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rightText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rightText, "00");
    lv_obj_set_style_text_color(ui_rightText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rightText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rightText, &ui_font_SS48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_middleLine = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_middleLine, 132);
    lv_obj_set_height(ui_middleLine, 3);
    lv_obj_set_align(ui_middleLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_middleLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_middleLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_middleLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_middleLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_middleLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_middleLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
